# Generated by Django 3.0.3 on 2020-03-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200313_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_secret',
            new_name='email_verification_key',
        ),
    ]
