# Generated by Django 3.0.3 on 2020-03-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_login_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_method',
            new_name='register_login_method',
        ),
    ]
