# Generated by Django 3.0.3 on 2020-02-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='location',
            new_name='accessibility',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='content',
        ),
    ]
